export const Bairros = [
    {label: 'Sé'  },
    {label:'Bela Vista'  },
    {label:'Bom Retiro' },
    {label:'Cambuci'  },
    {label:'Consolação'  },
    {label:'Liberdade'},
    {label:'República'},
    {label:'Santa Cecília'},
    {label:'Aricanduva'},
    {label:'Carrão'},
    {label:'Vila Formosa'},
    {label:'Cidade Tiradentes'},
    {label:'Ermelino Matarazzo'},
    {label:'Ponte Rasa'},
    {label:'Guaianases'},
    {label:'Lajeado'},
    {label:'Itaim Paulista'},
    {label:'Vila Curuçá'},
    {label:'Itaquera'},
    {label:'Cidade Líder'},
    {label:'José Bonifácio'},
    {label:'Parque do Carmo'},
    {label:'Mooca'},
    {label:'Água Rasa'},
    {label:'Belém'},
    {label:'Brás'},
    {label:'Pari'},
    {label:'Tatuapé'},
    {label:'Penha'},
    {label:'Artur Alvim'},
    {label:'Cangaíba'},
    {label:'Penha'},
    {label:'Vila Matilde'},
    {label:'São Mateus'},
    {label:'São Rafael'},
    {label:'São Miguel'},
    {label:'Jardim Helena'},
    {label:'Vila Jacuí'},
    {label:'Sapopemba'},
    {label:'Vila Prudente'},
    {label:'São Lucas'},
    {label:'Casa Verde'},
    {label:'Cachoeirinha'},
    {label:'Limão'},
    {label:'Brasilândia'},
    {label:' Freguesia do Ó'},
    {label:'Jaçanã'},
    {label:'Tremembé'},
    {label:'Perus'},
    {label:'Anhanguera'},
    {label:'Pirituba'},
    {label:'Jaraguá'},
    {label:'São Domingos'},
    {label:'Santana'},
    {label:'Tucuruvi'},
    {label:'Mandaqui'},
    {label:'Vila Maria'},
    {label:'Vila Guilherme'},
    {label:'Vila Medeiros'},
    {label:'Butantã'},
    {label:'Morumbi'},
    {label:'Raposo Tavares'},
    {label:'Rio Pequeno'},
    {label:'Vila Sônia'},
    {label:'Lapa'},
    {label:'Barra Funda'},
    {label:'Jaguara'},
    {label:'Jaguaré'},
    {label:'Perdizes'},
    {label:'Vila Leopoldina'},
    {label:'Pinheiros'},
    {label:'Alto de Pinheiros'},
    {label:'Itaim Bibi'},
    {label:'Jardim Paulista'},
    {label:'Campo Limpo'},
    {label:'Capão Redondo'},
    {label:'Vila Andrade'},
    {label:'Capela do Socorro'},
    {label:'Cidade Dutra'},
    {label:'Grajaú'},
    {label:'Socorro'},
    {label:'Cidade Ademar'},
    {label:'Pedreira'},
    {label:'Ipiranga'},
    {label:'Sacomã'},
    {label:'Jabaquara'},
    {label:'MBoi Mirim'},
    {label:'Jardim Ângela'},
    {label:'Jardim São Luís'},
    {label:'Parelheiros'},
    {label:'Marsilac'},
    {label:'Santo Amaro'},
    {label:'Campo Belo'},
    {label:'Campo Grande'},
    {label:'Moema'},
    {label:'Saúde'},
    {label:'Vila Mariana'},
    {label:'Jardim Elba'},
    {label:'São Roberto'},
    ]
    